### ISSUE TITLE
XML-documentation files are not included in the nuget

### ISSUE THREAD

**Issue by haf** [sestoft/C5#3]
Hi,

Glad you put it up on github in the end! :)

When using the nuget, there are no xml files in the package. There should be XML files so that we can get intellisense documentation for methods and types.

Regards

**Comment by hickford** [comment]
Hi. I think this has regressed, I can't find the xml docs in the current Nuget package http://www.nuget.org/packages/C5/2.3.0.1

@ondfisk could you fix as before?

**Comment by hickford** [comment]
Could you reopen?

**Comment by ondfisk** [comment]
Seems to be missing again

**Comment by ondfisk** [comment]
Done

**Comment by hickford** [comment]
Hi. Any progress? The current version is still missing xml documentation https://www.nuget.org/packages/C5/2.3.0.1

**Comment by ondfisk** [comment]
They should be there now

**Comment by hickford** [comment]
Yes I see, thanks https://www.nuget.org/packages/C5/
